<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/hotelbooking"
    xmlns="http://example.com/hotelbooking" elementFormDefault="qualified">

    <xs:element name="CreateClientRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateClientResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
                <xs:element name="name" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateRoomRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="price" type="xs:double"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="CreateRoomResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="price" type="xs:double"/>
                <xs:element name="available" type="xs:boolean"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ReserveRoomRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="clientId" type="xs:long"/>
                <xs:element name="roomIds" type="xs:long" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="ReserveRoomResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="reservationId" type="xs:long"/>
                <xs:element name="clientName" type="xs:string"/>
                <xs:element name="totalAmount" type="xs:double"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
