<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:tns="http://example.com/hotelbooking"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://example.com/hotelbooking" name="HotelBookingService">

    <types>
        <xsd:schema targetNamespace="http://example.com/hotelbooking">
            <xsd:element name="CreateClientRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="CreateClientResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="id" type="xsd:long"/>
                        <xsd:element name="name" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="CreateRoomRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string"/>
                        <xsd:element name="price" type="xsd:double"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="CreateRoomResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string"/>
                        <xsd:element name="price" type="xsd:double"/>
                        <xsd:element name="availability" type="xsd:boolean"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="ReserveRoomRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="clientId" type="xsd:long"/>
                        <xsd:element name="roomIds" type="xsd:long" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="ReserveRoomResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="reservationId" type="xsd:long"/>
                        <xsd:element name="clientName" type="xsd:string"/>
                        <xsd:element name="totalAmount" type="xsd:double"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="GetRoomDetailsRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="roomId" type="xsd:long"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="GetRoomDetailsResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="name" type="xsd:string"/>
                        <xsd:element name="price" type="xsd:double"/>
                        <xsd:element name="availability" type="xsd:boolean"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="CreateReservationRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="clientId" type="xsd:long"/>
                        <xsd:element name="roomIds" type="xsd:long" minOccurs="1" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="CreateReservationResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="confirmationMessage" type="xsd:string"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="GetAvailableRoomsRequest">
                <xsd:complexType/>
            </xsd:element>

            <xsd:element name="GetAvailableRoomsResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="rooms" type="tns:RoomInfo" minOccurs="0" maxOccurs="unbounded"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="GetClientReservationsRequest">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="clientId" type="xsd:long"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>

            <xsd:element name="GetClientReservationsResponse">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="rooms" type="tns:ReservedRoomDTO" minOccurs="0" maxOccurs="unbounded"/>
                        <xsd:element name="totalCost" type="xsd:double"/>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>


            <xsd:complexType name="RoomInfo">
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"/>
                    <xsd:element name="price" type="xsd:double"/>
                    <xsd:element name="availability" type="xsd:boolean"/>
                </xsd:sequence>
            </xsd:complexType>

        </xsd:schema>
    </types>

    <message name="CreateClientRequest">
        <part name="parameters" element="tns:CreateClientRequest"/>
    </message>
    <message name="CreateClientResponse">
        <part name="parameters" element="tns:CreateClientResponse"/>
    </message>
    <message name="GetRoomDetailsRequest">
        <part name="parameters" element="tns:GetRoomDetailsRequest"/>
    </message>
    <message name="GetRoomDetailsResponse">
        <part name="parameters" element="tns:GetRoomDetailsResponse"/>
    </message>

    <message name="CreateRoomRequest">
        <part name="parameters" element="tns:CreateRoomRequest"/>
    </message>
    <message name="CreateRoomResponse">
        <part name="parameters" element="tns:CreateRoomResponse"/>
    </message>

    <message name="ReserveRoomRequest">
        <part name="parameters" element="tns:ReserveRoomRequest"/>
    </message>
    <message name="ReserveRoomResponse">
        <part name="parameters" element="tns:ReserveRoomResponse"/>
    </message>

    <message name="CreateReservationRequest">
        <part name="parameters" element="tns:CreateReservationRequest"/>
    </message>
    <message name="CreateReservationResponse">
        <part name="parameters" element="tns:CreateReservationResponse"/>
    </message>
    <message name="GetAvailableRoomsRequest">
        <part name="parameters" element="tns:GetAvailableRoomsRequest"/>
    </message>

    <message name="GetAvailableRoomsResponse">
        <part name="parameters" element="tns:GetAvailableRoomsResponse"/>
    </message>

    <message name="GetClientReservationsRequest">
        <part name="parameters" element="tns:GetClientReservationsRequest"/>
    </message>
    <message name="GetClientReservationsResponse">
        <part name="parameters" element="tns:GetClientReservationsResponse"/>
    </message>


    <portType name="HotelBookingPortType">
        <operation name="CreateClient">
            <input message="tns:CreateClientRequest"/>
            <output message="tns:CreateClientResponse"/>
        </operation>
        <operation name="CreateRoom">
            <input message="tns:CreateRoomRequest"/>
            <output message="tns:CreateRoomResponse"/>
        </operation>
        <operation name="ReserveRoom">
            <input message="tns:ReserveRoomRequest"/>
            <output message="tns:ReserveRoomResponse"/>
        </operation>
        <operation name="GetRoomDetails">
            <input message="tns:GetRoomDetailsRequest"/>
            <output message="tns:GetRoomDetailsResponse"/>
        </operation>
        <operation name="CreateReservation">
            <input message="tns:CreateReservationRequest"/>
            <output message="tns:CreateReservationResponse"/>
        </operation>
        <operation name="GetAvailableRooms">
            <input message="tns:GetAvailableRoomsRequest"/>
            <output message="tns:GetAvailableRoomsResponse"/>
        </operation>
        <operation name="GetClientReservations">
            <input message="tns:GetClientReservationsRequest"/>
            <output message="tns:GetClientReservationsResponse"/>
        </operation>

    </portType>

    <binding name="HotelBookingBinding" type="tns:HotelBookingPortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CreateClient">
            <soap:operation soapAction="http://example.com/hotelbooking/CreateClient"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="CreateRoom">
            <soap:operation soapAction="http://example.com/hotelbooking/CreateRoom"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="ReserveRoom">
            <soap:operation soapAction="http://example.com/hotelbooking/ReserveRoom"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="GetRoomDetails">
            <soap:operation soapAction="http://example.com/hotelbooking/GetRoomDetails"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="CreateReservation">
            <soap:operation soapAction="http://example.com/hotelbooking/CreateReservation"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
        <operation name="GetAvailableRooms">
            <soap:operation soapAction="http://example.com/hotelbooking/GetAvailableRooms"/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>


    </binding>

    <service name="HotelBookingService">
        <port name="HotelBookingPort" binding="tns:HotelBookingBinding">
            <soap:address location="http://localhost:8080/ws/hotelbooking"/>
        </port>
    </service>
</definitions>